### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by tempus2016** [JimStar/reolink_cctv#165]
**Describe the bug**
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/reolink_cctv/binary_sensor.py:221
Integration: Reolink IP NVR/camera (documentation, issues)
First occurred: 03:38:23 (1 occurrences)
Last logged: 03:38:23

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1119, in _create_connection_transport
    await waiter
ConnectionAbortedError: SSL handshake is taking longer than 60.0 seconds: aborting the connection

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/reolink_cctv/binary_sensor.py", line 221, in handle_event
    await self._host.api.get_all_motion_states(self._channel)
  File "/usr/local/lib/python3.10/site-packages/reolink_ip/api.py", line 1075, in get_all_motion_states
    json_data = await self.send(body, expected_content_type = 'json')
  File "/usr/local/lib/python3.10/site-packages/reolink_ip/api.py", line 2502, in send
    raise e
  File "/usr/local/lib/python3.10/site-packages/reolink_ip/api.py", line 2455, in send
    response = await session.post(url = self._url, json = body, params = param, allow_redirects = False)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.82:443 ssl:default [None]
```

**Debug log would be very helpful**
If applicable, switch on debug-logging, and attach here a full log-file: from the HA restart, and covering the time where the issue happened.  
```
logger:
  default: warning
  logs:
    custom_components.reolink_cctv: debug
    reolink_ip: debug
```

**Environment:**
Home Assistant 2023.2.1
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest
RLN8-410
by Reolink
Firmware: v3.0.0.173_22041117
Hardware: N3MB01

**Additional context**
Have a few errors and warnings.

```
This error originated from a custom integration.

Logger: custom_components.reolink_cctv
Source: helpers/update_coordinator.py:182
Integration: Reolink IP NVR/camera (documentation, issues)
First occurred: 03:35:05 (1 occurrences)
Last logged: 03:35:05

Timeout fetching reolink.Driveway data
```

```
This error originated from a custom integration.

Logger: reolink_ip.api
Source: custom_components/reolink_cctv/sensor.py:209
Integration: Reolink IP NVR/camera (documentation, issues)
First occurred: 03:40:06 (1 occurrences)
Last logged: 03:40:06

Host 192.168.1.82:443: connection timeout exception. Please check the connection to this host.
```

```
This error originated from a custom integration.

Logger: reolink_ip.api
Source: custom_components/reolink_cctv/host.py:352
Integration: Reolink IP NVR/camera (documentation, issues)
First occurred: 03:41:45 (1 occurrences)
Last logged: 03:41:45

Host 192.168.1.82:443: subscription request got a response with wrong HTTP status 400: Bad Request
```

```
This error originated from a custom integration.

Logger: reolink_ip.api
Source: custom_components/reolink_cctv/host.py:214
Integration: Reolink IP NVR/camera (documentation, issues)
First occurred: 03:28:44 (3 occurrences)
Last logged: 05:31:35

Host 192.168.1.82:443: error mapping response to channels, received 1 responses while requesting 15.
Host 192.168.1.82:443: content type error: Error translating JSON response: Extra data: line 1 column 2 (char 1), content type 'text/html', data: 2FvUZB7vhSZcd+GImHDDoA7Umb+7ebJ2/3adIXZmjRzjivSEm2VT90VIy6vNa77OXbWnFm+AALEeF9tbhQgWBsS1/bvO4Y9K5PGoOl3K4oxmjbrLHTaM4zVmeq/+wYNyoGoob9WsRZiRkyq9w/t/ehIhqqD4YMDfiaNLLEbgYpw3kaCKTCuvLjI9b/RVrUTAqnfR+aw= .
Host: 192.168.1.82:443: error translating channels-states response.
```

```
This error originated from a custom integration.

Logger: reolink_ip.api
Source: custom_components/reolink_cctv/binary_sensor.py:221
Integration: Reolink IP NVR/camera (documentation, issues)
First occurred: 03:38:23 (3 occurrences)
Last logged: 07:22:17

Host 192.168.1.82:443: connection error: Cannot connect to host 192.168.1.82:443 ssl:default [None]
Host 192.168.1.82:443: content type error: Error translating JSON response: Extra data: line 1 column 5 (char 4), content type 'text/html', data: 45E4puZlSHbTfTENs8nbk7CgNedYCizu3J3QgYzseBnbvPqqaRkqAyNcw4gGw9WDJeVuCZ/UmWKlBb5188dMYkkAWwlxBUFbhLTGGP6s6DjrRdgSqFdSGnwlnfBtPL/+pvMhZ+GK1baws0fI15+Kh7XVjluFAEGTpiPZ0jUEfh93gMkt5mzhLrO1IIUjS43ev+NVIho= .
Host 192.168.1.82:443: error translating All Motion States response for channel 0.
```

```
This error originated from a custom integration.

Logger: reolink_ip.api
Source: custom_components/reolink_cctv/sensor.py:183
Integration: Reolink IP NVR/camera (documentation, issues)
First occurred: 07:22:17 (2 occurrences)
Last logged: 07:22:17

Host 192.168.1.82:443: content type error: Error translating JSON response: Extra data: line 1 column 5 (char 4), content type 'text/html', data: 45E4puZlSHbTfTENs8nbk7CgNedYCirl1oHcnsDiXjMG88US0QVLOmNQN2G8xydkDEeWIN+uF8hkix4BZviWzFUP4sI+UlswLDgkytxnm+mQoyD6hGO8oF6tv/wSOFY9Zp/lMWID7U3IqbUG9ahTRq8WnIoxezwTv8QYxlG5qI/syHlhtKkggZLJI5pYytitrqEe+w== .
Host 192.168.1.82:443: error translating of "Search" command response.
```

**Comment by JimStar** [comment]
This is not this component's error. These messages show the component is unable to make a connection to your device.  
It looks like some issue in your network setup...
