### ISSUE TITLE
Error executing service

### ISSUE THREAD

**Issue by tempus2016** [JimStar/reolink_cctv#166]
```
This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/reolink_cctv/camera.py:219 
Integration: Reolink IP NVR/camera (documentation, issues) 
First occurred: 03:14:49 (3 occurrences) 
Last logged: 03:26:49

Error executing service: <ServiceCall camera.snapshot (c:01GRT2NNCM6YXFWS7J9G6DNGTD): entity_id=['camera.driveway_sub'], filename=Template("/config/.storage/reolink_cctv/5cc3362dc6f1/0/1675912425.0.jpg")>
Error executing service: <ServiceCall camera.snapshot (c:01GRT38XTAYBJ5D2CBFJRK44AM): entity_id=['camera.driveway_sub'], filename=Template("/config/.storage/reolink_cctv/5cc3362dc6f1/0/1675913051.0.jpg")>
Error executing service: <ServiceCall camera.snapshot (c:01GRT39M16RYK2BWFFP5BXD7A2): entity_id=['camera.driveway_sub'], filename=Template("/config/.storage/reolink_cctv/5cc3362dc6f1/0/1675913101.0.jpg")>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1805, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 720, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 915, in async_handle_snapshot_service
    image = await camera.async_camera_image()
  File "/config/custom_components/reolink_cctv/camera.py", line 219, in async_camera_image
    return await self._host.api.get_snapshot(self._channel)
  File "/usr/local/lib/python3.10/site-packages/reolink_ip/api.py", line 1137, in get_snapshot
    response = await self.send(None, param, expected_content_type = 'image/jpeg')
  File "/usr/local/lib/python3.10/site-packages/reolink_ip/api.py", line 2518, in send
    raise e
  File "/usr/local/lib/python3.10/site-packages/reolink_ip/api.py", line 2484, in send
    raise InvalidContentTypeError("Expected type '{}' but received '{}'.".format(expected_content_type, response.content_type))
reolink_ip.exceptions.InvalidContentTypeError: Expected type 'image/jpeg' but received 'text/html'.
```
Only just started, never seen this error pop up before. RLC-410W camera.

**Comment by JimStar** [comment]
This is some erratic data returned by the camera instead of proper image data. I've seen something like this episodically happening before in some Reolink devices, looks like some fluctuating Reolink firmware bug...
