### ISSUE TITLE
Expected type 'image/jpeg' but received 'text/html'

### ISSUE THREAD

**Issue by garry0garry** [JimStar/reolink_cctv#200]
`reolink_ip.exceptions.InvalidContentTypeError: Expected type 'image/jpeg' but received 'text/html'`

Hello!
Can you please tell me how to find out what exactly is passed in HTML? This does not happen often, but what to do is completely incomprehensible.

```
Logger: homeassistant
Source: custom_components/reolink_cctv/camera.py:219
Integration: Reolink IP NVR/camera (documentation, issues)
First occurred: 08:53:06 (2 occurrences)
Last logged: 09:31:54

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/reolink_cctv/sensor.py", line 248, in _update_last_record
    await self._hass.services.async_call(CAMERA_DOMAIN, SERVICE_SNAPSHOT, service_data, blocking = True)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 930, in async_handle_snapshot_service
    image = await camera.async_camera_image()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/reolink_cctv/camera.py", line 219, in async_camera_image
    return await self._host.api.get_snapshot(self._channel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/reolink_ip/api.py", line 1137, in get_snapshot
    response = await self.send(None, param, expected_content_type = 'image/jpeg')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/reolink_ip/api.py", line 2518, in send
    raise e
  File "/usr/local/lib/python3.11/site-packages/reolink_ip/api.py", line 2484, in send
    raise InvalidContentTypeError("Expected type '{}' but received '{}'.".format(expected_content_type, response.content_type))
reolink_ip.exceptions.InvalidContentTypeError: Expected type 'image/jpeg' but received 'text/html'.

```

**Comment by JimStar** [comment]
You'd need to change the component's code for that. But because it doesn't matter for the component what exact garbage is sent by the buggy Reolink device in response instead of image data - I don't see any sense to spend time and effort on that...

**Comment by garry0garry** [comment]
At the time of this error, the camera was available through an application on a smartphone and from a computer. Maybe a traffic dump will tell you something new?

Request HA -> Cam13
`    GET /cgi-bin/api.cgi?cmd=Snap&channel=0&token=xxxxxxxxxxxxxx HTTP/1.1\r\n
`    

Response Cam13 -> HA
```
    POST /api/webhook/reolink_cam13_webhook HTTP/1.1\r\n
eXtensible Markup Language
    <?xml
        version="1.0"
        encoding="UTF-8"
        ?>
    <SOAP-ENV:Envelope
        xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope"
        xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing"
        xmlns:wsdd="http://schemas.xmlsoap.org/ws/2005/04/discovery"
        xmlns:xop="http://www.w3.org/2004/08/xop/include"
        xmlns:chan="http://schemas.microsoft.com/ws/2005/02/duplex"
        xmlns:wsa5="http://www.w3.org/2005/08/addressing"
        xmlns:c14n="http://www.w3.org/2001/10/xml-exc-c14n#"
        xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
        xmlns:saml1="urn:oasis:names:tc:SAML:1.0:assertion"
        xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"
        xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
        xmlns:xenc="http://www.w3.org/2001/04/xmlenc#"
        xmlns:wsc="http://docs.oasis-open.org/ws-sx/ws-secureconversation/200512"
        xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
        xmlns:tt="http://www.onvif.org/ver10/schema"
        xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2"
        xmlns:wstop="http://docs.oasis-open.org/wsn/t-1"
        xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2"
        xmlns:ns1="http://www.onvif.org/ver20/media/wsdl"
        xmlns:tdn="http://www.onvif.org/ver10/network/wsdl"
        xmlns:tds="http://www.onvif.org/ver10/device/wsdl"
        xmlns:tev="http://www.onvif.org/ver10/events/wsdl"
        xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2"
        xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl"
        xmlns:tmd="http://www.onvif.org/ver10/deviceIO/wsdl"
        xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl"
        xmlns:trc="http://www.onvif.org/ver10/recording/wsdl"
        xmlns:trp="http://www.onvif.org/ver10/replay/wsdl"
        xmlns:trt="http://www.onvif.org/ver10/media/wsdl"
        xmlns:trv="http://www.onvif.org/ver10/receiver/wsdl"
        xmlns:tse="http://www.onvif.org/ver10/search/wsdl"
        xmlns:ter="http://www.onvif.org/ver10/error"
        xmlns:tns1="http://www.onvif.org/ver10/topics"
        xmlns:tad="http://www.onvif.org/ver20/analytics/wsdl">
        <SOAP-ENV:Header>
            <wsa5:Action
            </SOAP-ENV:Header>
        <SOAP-ENV:Body>
            <wsnt:Notify>
            </SOAP-ENV:Body>
        </SOAP-ENV:Envelope>

```

**Comment by garry0garry** [comment]
Collected traffic dumps and attached the log. Can I send the log privately?

**Comment by JimStar** [comment]
Logs/damps don't make sense for me in this case. Because this is clearly a **Reolink bug**, it must be reported **to Reolink** and must be fixed by Reolink in their firmware. I already said this before.  
I see in your previous post that the camera just sends an empty ONVIF envelope in response to a proper snapshot request (instead of image data). Nothing to do with this component.
