### ISSUE TITLE
lot of errors, but still work, so not a big deal ;)

### ISSUE THREAD

**Issue by Electronlibre2012** [JimStar/reolink_cctv#57]
Hello @JimStar 

just for info, i have several errors :

1-Host 192.168.1.174:8091: subscription request got a response with wrong HTTP status 400: Bad Request
2-Host 192.168.1.174:8091: login attempt failed.
3-Unexpected error fetching reolink.REOLINK NVR data: 
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/reolink_cctv/__init__.py", line 104, in async_device_config_update
    await host.update_states() # Login session is implicitly updated here, so no need to explicitly do it in a timer
  File "/config/custom_components/reolink_cctv/host.py", line 201, in update_states
    return await self._api.get_states()
  File "/usr/local/lib/python3.10/site-packages/reolink_ip/api.py", line 818, in get_states
    response = await self.send(body)
  File "/usr/local/lib/python3.10/site-packages/reolink_ip/api.py", line 2186, in send
    raise e
  File "/usr/local/lib/python3.10/site-packages/reolink_ip/api.py", line 2165, in send
    raise CredentialsInvalidError()
reolink_ip.exceptions.CredentialsInvalidError
```
4-Can't write /config/.storage/reolink_cctv/ca4b487dc354e8727a198e9d442a385c/1/1668263918.0.jpg, no access to path!

i change nothing, just add a new external HDD on e-sata port but that was 2 days ago.

**Comment by JimStar** [comment]
Login/credentials errors are most likely the known Reolink issues - it has no way to exit the previous "stuck" sessions. So before some session expires letting a new one started by a client, it just keeps failing with any login attempts.  
Same about failed subscriptions: Reolink has limited amount of subscirptions, so if there are any previous active - it would keep failing with any new ones, before the previous expire... No way to force-exit the "stuck" ones.
"No access to path" - again it doesn't look like the component's issue, it just tries to write to a path that is unaccessible for writing...

Anyway I need a full debug log (starting with a HA restart) to say more...

**Comment by Electronlibre2012** [comment]
ok thanks to your reply!

tomorow i will see if there is some more errors and take time to give you a full debug log.

**Comment by JimStar** [comment]
Feel free to reopen this after the debug log gets attached...
